language: "perl"
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

install:
  # required modules
  - cpanm IO::File
  - cpanm BibTeX::Parser
  - cpanm Text::Unidecode

script: 
  - perl apply_references.pl test/refs.bib test/new.md.ref output.md
  - diff test/output-expected.md output.md
